import type { CategoryDef } from "../types";

export const CATEGORIES: CategoryDef[] = [
  {
    id: "general",
    slug: "general-knowledge",
    name: { ar: "معلومات عامة", en: "General Knowledge" },
    description: { ar: "أسئلة متنوعة من كل المجالات", en: "A mix of everyday trivia" },
    icon: "globe",
    color: "#FFB7CE",
    accentColor: "#FFD4E0",
    image: "/categories/general.svg",
  },
  {
    id: "history",
    slug: "history",
    name: { ar: "تاريخ", en: "History" },
    description: { ar: "أحداث وحضارات وشخصيات تاريخية", en: "Events, civilizations, and figures" },
    icon: "scroll",
    color: "#8B5E3C",
    accentColor: "#D4A574",
    image: "/categories/history.svg",
  },
  {
    id: "geography",
    slug: "geography",
    name: { ar: "جغرافيا", en: "Geography" },
    description: { ar: "دول وعواصم ومعالم", en: "Countries, capitals, landmarks" },
    icon: "map",
    color: "#2E7D4F",
    accentColor: "#6BCB77",
    image: "/categories/geography.svg",
  },
  {
    id: "science",
    slug: "science",
    name: { ar: "علوم", en: "Science" },
    description: { ar: "فيزياء وكيمياء وأحياء", en: "Physics, chemistry, biology" },
    icon: "flask",
    color: "#1565C0",
    accentColor: "#64B5F6",
    image: "/categories/science.svg",
  },
  {
    id: "technology",
    slug: "technology",
    name: { ar: "تكنولوجيا", en: "Technology" },
    description: { ar: "أجهزة وإنترنت وابتكار", en: "Gadgets, internet, innovation" },
    icon: "cpu",
    color: "#455A64",
    accentColor: "#90A4AE",
    image: "/categories/technology.svg",
  },
  {
    id: "sports",
    slug: "sports",
    name: { ar: "رياضة", en: "Sports" },
    description: { ar: "ألعاب ومنافسات وأبطال", en: "Games, tournaments, champions" },
    icon: "trophy",
    color: "#F57C00",
    accentColor: "#FFB74D",
    image: "/categories/sports.svg",
  },
  {
    id: "football",
    slug: "football",
    name: { ar: "كرة قدم", en: "Football" },
    description: { ar: "أندية ومنتخبات وكؤوس", en: "Clubs, nations, and cups" },
    icon: "soccer",
    color: "#1B5E20",
    accentColor: "#66BB6A",
    image: "/categories/football.svg",
  },
  {
    id: "movies",
    slug: "movies",
    name: { ar: "أفلام", en: "Movies" },
    description: { ar: "سينما عربية وعالمية", en: "Arabic and world cinema" },
    icon: "film",
    color: "#6A1B9A",
    accentColor: "#CE93D8",
    image: "/categories/movies.svg",
  },
  {
    id: "tv",
    slug: "tv-shows",
    name: { ar: "مسلسلات", en: "TV Shows" },
    description: { ar: "دراما وكوميديا وبرامج", en: "Drama, comedy, and shows" },
    icon: "tv",
    color: "#AD1457",
    accentColor: "#F48FB1",
    image: "/categories/tv.svg",
  },
  {
    id: "anime",
    slug: "anime",
    name: { ar: "أنمي", en: "Anime" },
    description: { ar: "أنمي ومانجا وشخصيات", en: "Anime, manga, and characters" },
    icon: "sparkles",
    color: "#E91E63",
    accentColor: "#F8BBD9",
    image: "/categories/anime.svg",
  },
  {
    id: "music",
    slug: "music",
    name: { ar: "موسيقى", en: "Music" },
    description: { ar: "أغاني وفنانين وآلات", en: "Songs, artists, instruments" },
    icon: "music",
    color: "#00838F",
    accentColor: "#4DD0E1",
    image: "/categories/music.svg",
  },
  {
    id: "celebrities",
    slug: "celebrities",
    name: { ar: "مشاهير", en: "Celebrities" },
    description: { ar: "وجوه شهيرة من كل المجالات", en: "Famous faces across fields" },
    icon: "star",
    color: "#F9A825",
    accentColor: "#FFE082",
    image: "/categories/celebrities.svg",
  },
  {
    id: "arab-culture",
    slug: "arab-culture",
    name: { ar: "ثقافة عربية", en: "Arab Culture" },
    description: { ar: "تراث وعادات ولهجات", en: "Heritage, customs, dialects" },
    icon: "mosque",
    color: "#BF360C",
    accentColor: "#FF8A65",
    image: "/categories/arab-culture.svg",
  },
  {
    id: "islamic",
    slug: "islamic-culture",
    name: { ar: "ثقافة إسلامية", en: "Islamic Culture" },
    description: { ar: "تاريخ إسلامي ومفاهيم دينية عامة", en: "Islamic history and general knowledge" },
    icon: "crescent",
    color: "#004D40",
    accentColor: "#26A69A",
    image: "/categories/islamic.svg",
  },
  {
    id: "food",
    slug: "food",
    name: { ar: "مأكولات", en: "Food" },
    description: { ar: "أطباق ومكونات ومطابخ", en: "Dishes, ingredients, cuisines" },
    icon: "utensils",
    color: "#E65100",
    accentColor: "#FFAB91",
    image: "/categories/food.svg",
  },
  {
    id: "countries",
    slug: "countries",
    name: { ar: "دول", en: "Countries" },
    description: { ar: "دول العالم وحقائقها", en: "World countries and facts" },
    icon: "flag",
    color: "#283593",
    accentColor: "#9FA8DA",
    image: "/categories/countries.svg",
  },
  {
    id: "animals",
    slug: "animals",
    name: { ar: "حيوانات", en: "Animals" },
    description: { ar: "عالم الحيوان والطبيعة", en: "Wildlife and nature" },
    icon: "paw",
    color: "#558B2F",
    accentColor: "#AED581",
    image: "/categories/animals.svg",
  },
  {
    id: "brands",
    slug: "brands",
    name: { ar: "علامات تجارية", en: "Brands" },
    description: { ar: "شعارات وشركات ومنتجات", en: "Logos, companies, products" },
    icon: "tag",
    color: "#37474F",
    accentColor: "#B0BEC5",
    image: "/categories/brands.svg",
  },
  {
    id: "gaming",
    slug: "gaming",
    name: { ar: "ألعاب إلكترونية", en: "Gaming" },
    description: { ar: "ألعاب ومنصات وشخصيات", en: "Games, platforms, characters" },
    icon: "gamepad",
    color: "#6A1B9A",
    accentColor: "#B39DDB",
    image: "/categories/gaming.svg",
  },
  {
    id: "cars",
    slug: "cars",
    name: { ar: "سيارات", en: "Cars" },
    description: { ar: "ماركات ومحركات وسباقات", en: "Makes, engines, racing" },
    icon: "car",
    color: "#212121",
    accentColor: "#9E9E9E",
    image: "/categories/cars.svg",
  },
  {
    id: "space",
    slug: "space",
    name: { ar: "فضاء", en: "Space" },
    description: { ar: "كواكب ونجوم واستكشاف", en: "Planets, stars, exploration" },
    icon: "rocket",
    color: "#1A237E",
    accentColor: "#7986CB",
    image: "/categories/space.svg",
  },
  {
    id: "literature",
    slug: "literature",
    name: { ar: "أدب", en: "Literature" },
    description: { ar: "كتب وشعراء وروايات", en: "Books, poets, novels" },
    icon: "book",
    color: "#4E342E",
    accentColor: "#A1887F",
    image: "/categories/literature.svg",
  },
  {
    id: "languages",
    slug: "languages",
    name: { ar: "لغات", en: "Languages" },
    description: { ar: "كلمات ومعاني ولهجات", en: "Words, meanings, dialects" },
    icon: "languages",
    color: "#00695C",
    accentColor: "#80CBC4",
    image: "/categories/languages.svg",
  },
  {
    id: "riddles",
    slug: "riddles",
    name: { ar: "ألغاز", en: "Riddles" },
    description: { ar: "ألغاز وتحديات ذهنية", en: "Brain teasers and riddles" },
    icon: "puzzle",
    color: "#5D4037",
    accentColor: "#BCAAA4",
    image: "/categories/riddles.svg",
  },
  {
    id: "math",
    slug: "mathematics",
    name: { ar: "رياضيات", en: "Mathematics" },
    description: { ar: "أرقام ومعادلات ومنطق", en: "Numbers, equations, logic" },
    icon: "calculator",
    color: "#0277BD",
    accentColor: "#4FC3F7",
    image: "/categories/math.svg",
  },
  {
    id: "random",
    slug: "random-facts",
    name: { ar: "حقائق عشوائية", en: "Random Facts" },
    description: { ar: "حقائق غريبة ومفاجئة", en: "Weird and surprising facts" },
    icon: "shuffle",
    color: "#C62828",
    accentColor: "#EF9A9A",
    image: "/categories/random.svg",
  },
  {
    id: "logos",
    slug: "logos",
    name: { ar: "شعارات", en: "Logos" },
    description: {
      ar: "خمّن العلامة من الشعار — أسئلة بالصور",
      en: "Guess the brand from its logo — image questions",
    },
    icon: "badge",
    color: "#263238",
    accentColor: "#90A4AE",
    image: "/categories/logos.svg",
  },
  {
    id: "songs",
    slug: "songs",
    name: { ar: "أغاني", en: "Songs" },
    description: {
      ar: "استمع للمقطع وخمّن الأغنية أو الفنان",
      en: "Listen and guess the song or artist",
    },
    icon: "headphones",
    color: "#6A1B9A",
    accentColor: "#CE93D8",
    image: "/categories/songs.svg",
  },
  {
    id: "clips",
    slug: "clips",
    name: { ar: "مقاطع", en: "Clips" },
    description: {
      ar: "مشاهد فيديو قصيرة من فن ورياضة وترفيه",
      en: "Short video clips from entertainment and sports",
    },
    icon: "clapperboard",
    color: "#B71C1C",
    accentColor: "#EF9A9A",
    image: "/categories/clips.svg",
  },
  {
    id: "flags",
    slug: "flags",
    name: { ar: "أعلام", en: "Flags" },
    description: {
      ar: "خمّن الدولة من علمها",
      en: "Guess the country from its flag",
    },
    icon: "flag",
    color: "#0D47A1",
    accentColor: "#90CAF9",
    image: "/categories/flags.svg",
  },
  {
    id: "kuwait",
    slug: "kuwait",
    name: { ar: "الكويت", en: "Kuwait" },
    description: {
      ar: "تاريخ وجغرافيا وثقافة كويتية",
      en: "Kuwaiti history, geography, and culture",
    },
    icon: "landmark",
    color: "#006C35",
    accentColor: "#CE1126",
    image: "/categories/kuwait.svg",
  },
];

export function getCategory(id: string): CategoryDef | undefined {
  return CATEGORIES.find((c) => c.id === id);
}
